const ERROR_SERVER = 500;
const ERROR_BAD_REQ = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;

module.exports = {
  ERROR_SERVER,
  ERROR_BAD_REQ,
  ERROR_NOT_FOUND,
  ERROR_UNAUTHORIZED,
  ERROR_FORBIDDEN,
};
